# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffff1bba260e7a55f2ccc8991cf97c17902409cc67222db4efedc1810f23c8f7ebe619c5f13871419c92472c7858f364146b7ee285ea1056c4fa1f8ec4f72e12

test:
  secret_key_base: cbdb3747fa3cf77a09c8972af66dff50e0ca96624347df7c4bd04255b46a3f4cb200c95ab817bcc8585f8cfb20a05bc7c73fac68e34d86b5ae0aabe7c46e13ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_APP_ID"] %>
  twitter_api_secret: <%= ENV["TWITTER_APP_SECRET"] %>

